version: "3"

services:
  helpdeskhero:
    build: ./helpdeskhero
    ports:
      - "3000:3000"
    volumes:
      - helpdeskhero:/helpdeskhero
    depends_on:
      - db

  api:
    build: ./api
    ports:
      - "8080:8080"
    environment:
      DB_CONNECTION_STRING: "postgres://postgres:docker@db:5432/helpdesk_tracker"
      secret: "asdlkfj324lkajfd"
    depends_on:
    - db
    volumes:
    - api:/api

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: helpdesk_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  db_data:
    build: ./db_data
    volumes:
      - db_data:/db_data
    depends_on:
      - db

volumes:
  db_data:
  db:
  helpdeskhero:
  api: