version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: helpdesk_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  db_data:
    build: './db_data'
    volumes:
      - db_data:/db_data
    depends_on:
      - db
volumes:
  db:
  db_data: